# Generated by Django 5.2.6 on 2025-09-06 13:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BSC', 'Binance Smart Chain'), ('USDT', 'Tether'), ('USDC', 'USD Coin')], max_length=10)),
                ('wallet_address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_in_crypto', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('transaction_hash', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='deposit_screenshots/')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deposits', to=settings.AUTH_USER_MODEL)),
                ('crypto_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_app.cryptowallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
