# Generated by Django 5.2.6 on 2025-09-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0003_userprofile_country_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentplan',
            options={'ordering': ['min_deposit']},
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], max_length=100, unique=True),
        ),
    ]
