# Generated by Django 5.2.6 on 2025-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0004_alter_investmentplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('confirm', 'Comfirm'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
