# Generated by Django 5.2.6 on 2025-09-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0007_alter_investment_options_investment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
