# Generated by Django 5.2.6 on 2025-09-20 11:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0008_alter_investment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='today_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
